### ISSUE TITLE
CrashLoopBackOff on mongodb-mongos-deployment-service.yaml

### ISSUE THREAD

**Issue by robertocandelu** [sunnykrGupta/gke-mongodb-shards#2]
When try to apply mongodb-mongos-deployment-service.yaml we got CrashLoopBackOff on my google cloud kubernetes cluster.

**Comment by sunnykrGupta** [comment]
Did you used script to apply mongodb-mongos-deployment-service.yaml changes or used directly? Script contains some changes needs to be done before apply.

**Comment by robertocandelu** [comment]
Hello, thank you for your quick answer. I used directly without script. I
have mongo-configdb and two shard pods up and running. I used the default
settings followed in your guide "
https://medium.com/google-cloud/sharded-mongodb-in-kubernetes-statefulsets-on-gke-ba08c7c0c0b0"
all done until mongos deployment.

The logs of my pods are:
mongos-container May 8, 2018, 3:05:43 PM BadValue: configdb supports only
replica set connection string


2018-05-08 13:35 GMT+02:00 SUNNY <notifications@github.com>:

**Comment by robertocandelu** [comment]
The logs of my pods are:
mongos-container May 8, 2018, 3:05:43 PM BadValue: configdb supports only
replica set connection string

*Roberto Candelù*
*IT e Tecnologie*

Isola Nuova del Tronchetto n.34 - 30135 Venezia
Tel. +39 041 2401.752 - Mob. +39 3386003287
ll presente messaggio, corredato dei relativi allegati, contiene
informazioni strettamente riservate ai destinatari.
Ai sensi del D.Lgs. 196/2003 chiunque ricevesse questo messaggio per errore
è invitato ad eliminarlo e a darne
immediata comunicazione al mittente. Ne è vietata la copia e la
divulgazione.
This message and any files transmitted with it are confidential and
intended only for use by the intended recipients
to whom they are addressed. Pursuant to Legislative Decree No. 196/2003
(Privacy Act) if you received this mail
in error please delete it and promptly notify us. You may not copy, deliver
or redistribute this message.


2018-05-08 14:36 GMT+02:00 Roberto Candelù <roberto.candelu@alilaguna.it>:

**Comment by sunnykrGupta** [comment]
Use it with the script only. Script make changes to "namespace" and "--configdb" parameter used in mongos yaml file. 

Please share your resources by running belong command
`
kubectl get svc,po,sts --namespace=<NAMESPACE> 
`

**Comment by sunnykrGupta** [comment]
In case if that doesn't help, you can use https://github.com/sunnykrGupta/gke-mongodb-shards/blob/master/scripts/generate-all.sh to run and build entire setup from a single script.

**Comment by robertocandelu** [comment]
My resources are follow: 
NAME                                    TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
svc/mongodb-configdb-headless-service   ClusterIP   None         <none>        27019/TCP   3h
svc/mongodb-shard1-headless-service     ClusterIP   None         <none>        27017/TCP   3h
svc/mongodb-shard2-headless-service     ClusterIP   None         <none>        27017/TCP   3h

NAME                    READY     STATUS    RESTARTS   AGE
po/mongodb-configdb-0   1/1       Running   0          3h
po/mongodb-shard1-0     1/1       Running   0          3h
po/mongodb-shard2-0     1/1       Running   0          3h

NAME                            DESIRED   CURRENT   AGE
statefulsets/mongodb-configdb   1         1         3h
statefulsets/mongodb-shard1     1         1         3h
statefulsets/mongodb-shard2     1         1         3h

**Comment by sunnykrGupta** [comment]
What version of kubernetes master you are running in GCP?  Let me retry this project again on my end. Can you share your deployment yaml file which you have applied to create mongos deployment.?

**Comment by robertocandelu** [comment]
Master version 1.8.8-gke.0
Here my deployment yaml file:

`apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongos
  namespace: daemonsl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        role: mongos
        tier: routers
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - routers
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongos-container
          image: mongo
          command:
            - "mongos"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--configdb"
            - "mongodb-configdb-0.mongodb-configdb-headless-service.daemonsl.svc.cluster.local:27019"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017`

**Comment by sunnykrGupta** [comment]
@robertocandelu  Sorry for late response, I ran the project in my kubernetes and turns out after 3.4 mongo version, configDB must be a member of replicaSet. 
https://docs.mongodb.com/v3.4/tutorial/upgrade-config-servers-to-replica-set/ . 

So, I guess this setup is limited upto mongo 3.2. I tested with docker 3.2 and it's working as expected.
